apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: application4-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application4-image
  policy:
    latest: {}
