apiVersion: source.toolkit.fluxcd.io/v2
kind: GitRepository
metadata:
  name: application3-repo
  namespace: flux-system  # GitRepository is in flux-system
spec:
  interval: 5m
  url: https://github.com/NaeemDosh/application3
  ref:
    branch: main
