apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: application3-repo
  namespace: default  # Make sure this is in the 'default' namespace
spec:
  url: https://github.com/NaeemDosh/application3
  ref:
    branch: main
