apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: application3-repo
  namespace: default
spec:
  interval: 1m
  url: https://github.com/NaeemDosh/application3
  ref:
    branch: main
  secretRef:
    name: flux-system-git-ssh
