apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: application3-repo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/NaeemDosh/application3.git
  ref:
    branch: main
