apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: application3  # Matches the chart directory name inside the repository
      sourceRef:
        kind: GitRepository
        name: application3-repo
        namespace: default
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: latest
