apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: application3  # Chart name in the application3 repository
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Correct GitRepository reference
        namespace: flux-system
      path: ./charts/application3  # Correct path to the chart in the repo
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: # {"$imagepolicy": "default:application3-image-policy"}
