apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/application3  # Path to Helm chart in the repo
      sourceRef:
        kind: GitRepository
        name: flux-deployments
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: # {"$imagepolicy": "default:application3-image-policy"}
