apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: application3 # Name of the chart (must match the chart in your Git repo)
      sourceRef:
        kind: GitRepository
        name: application3-repo
        namespace: flux-system # This is where the GitRepository resource is located
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      pullPolicy: IfNotPresent
      tag: latest
