apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: charts  # Path to the Helm chart
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Matches GitRepository
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      pullPolicy: Always  # Always pull the latest image
      tag: latest  # Set to 'latest' tag so Flux picks up any update
