apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: application3  # Ensure the chart is named correctly
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Correct reference to the GitRepo
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: # {"$imagepolicy": "default:application3-image-policy"}
