apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: .  # Use "." since the chart is in the same directory as `Chart.yaml`
      sourceRef:
        kind: GitRepository
        name: application3-repo
        namespace: default
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "latest"
