apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts              # Use the same chart name as in HelmChart
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Reference the correct GitRepository
        namespace: flux-system   # Namespace of GitRepository
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "latest"
