apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: application3-chart
  namespace: flux-system
spec:
  chart: charts
  sourceRef:
    kind: GitRepository
    name: application3-repo  # This should match the name of your GitRepository resource
    namespace: flux-system
  interval: 5m
