apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: application3-chart
  namespace: default
spec:
  chart: charts  # The directory or chart name in the Git repository
  sourceRef:
    kind: GitRepository
    name: application3-repo
    namespace: flux-system
  interval: 1m  # How often to check for changes
  valuesFile: values.yaml  # Optional, specifies which values file to use
