apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts  # This should point to the location of your chart
      sourceRef:
        kind: GitRepository
        name: application3-repo
      version: "0.1.0"  # You can specify the version of the chart, or use a latest tag.
  valuesFrom:
    - configMapKeyRef:
        name: application3-values
        key: values.yaml
  values:
    image:
      tag: "{{ .Values.image.tag }}"
  interval: 5m
  releaseName: application3
  install:
    createNamespace: true
