apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: application3  # This refers to the chart name within the repository
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Ensure this matches the GitRepository name
        namespace: default
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "latest"
