apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
  annotations:
    image.toolkit.fluxcd.io/update: "application3-policy"
spec:
  interval: 5m
  chart:
    spec:
      chart: charts
      sourceRef:
        kind: GitRepository
        name: application3-repo
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "v1.1.1"
