apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default  # Change this to default namespace
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/application3  # Path to Helm chart in the repo
      sourceRef:
        kind: GitRepository
        name: flux-deployments  # Ensure this GitRepository exists in flux-system namespace
        namespace: flux-system  # Keep this as flux-system for the GitRepository
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: # {"$imagepolicy": "default:application3-image-policy"}
