apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: application3  # Name of the chart in the Git repository
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Git repository reference
        namespace: default
      ref:
        branch: main  # Specify the branch (if needed)
      path: charts/application3  # Path to the Helm chart within the repository
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "latest"
