apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/application3  # Path to Helm chart in the repo
      sourceRef:
        kind: GitRepository
        name: application3-repo
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "v1.3.1"
