apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/application3  # Path to Helm chart
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Git repository containing Helm chart
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3  # Docker repository
      tag: latest  # This will be automatically updated by Flux when a new tag is found
