apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default  # Deploy the application in the default namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: application3-chart  # This should match the HelmChart name
      sourceRef:
        kind: HelmChart
        name: application3-chart  # Reference HelmChart in flux-system namespace
        namespace: flux-system  # HelmChart resides in flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "latest"
