apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/application3  # Path to your Helm chart inside the Git repository
      sourceRef:
        kind: GitRepository
        name: application3-repo  # Name of the Git repository that contains your Helm chart
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3  # Docker image repository
      tag: "latest"   # {"$imagepolicy": "docker.io/muhammadnaeem42/application3:tag"}
