apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: application3
  namespace: default  # This is where the application will be deployed
spec:
  interval: 5m
  chart:
    spec:
      chart: application3-chart  # Ensure this matches the chart name in the GitRepository
      sourceRef:
        kind: GitRepository  # Referencing GitRepository
        name: application3-repo  # Name of the GitRepository
        namespace: flux-system  # GitRepository is in the flux-system namespace
  values:
    image:
      repository: docker.io/muhammadnaeem42/application3
      tag: "latest"
