apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: application3-repository  # Refers to the ImageRepository
  policy:
    semver:
      range: "0.0.0-latest"  # This matches all versions, including 'latest'
