apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: default
spec:
  git:
    checkout:
      ref:
        branch: main  # Specify the branch to track
    commit:
      author:
        email: m.naeem.uet.cs@gmail.com
        name: NaeemDosh
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main  # Specify the branch to push changes
  interval: 1m0s  # Automation interval
  sourceRef:
    kind: GitRepository
    name: flux-deployments  # Ensure this GitRepository exists in flux-system
    namespace: flux-system
  update:
    path: .
    strategy: Setters  # Use Setters to replace values in YAML files
