apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux-bot@users.noreply.github.com
        name: Flux Bot
      messageTemplate: |
        Automated update for image {{ .Updated.ImageRef }}
    push:
      branch: main
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: application3-repo
  update:
    path: "./application3/helmrelease.yaml"  # Point to your HelmRelease
    strategy: Setters
