apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: application3-repo  # Name of the GitRepository resource
  update:
    path: charts  # Ensure this path points to the directory containing the HelmRelease file
    strategy: Setters
  git:
    checkout:
      ref:
        branch: main  # Replace with the branch you're using
    push:
      branch: main  # Replace with the branch you're using
    commit:
      author:
        email: flux-bot@users.noreply.github.com
        name: Flux Bot
      messageTemplate: |
        Automated image update for {{ .Updated.ImageRef }}
