apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-repository  # Reference the ImageRepository
  policy:
    semver:
      range: ">=1.0.0"  # Correct format for semver range
