apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: default
spec:
  interval: 5m  # How often to check for new images
  update:
    path: "./charts/application3/values.yaml"  # Path to update the values.yaml or other manifests
    strategy: Setters  # The strategy for updating the image tag in values.yaml
  git:
    secretRef:
      name: flux-system-git-ssh  # Secret containing SSH key for Git access
    repository: https://github.com/NaeemDosh/application3  # Git repository
    branch: main  # The Git branch to update
  image:
    policy:
      name: latest-policy  # Reference to the ImagePolicy to track the latest image
    tag: "latest"  # Ensure the 'latest' tag is used
