apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: default
spec:
  git:
    checkout:
      ref:
        branch: main  # Specify the branch you want to track for changes
    commit:
      author:
        email: m.naeem.uet.cs@gmail.com
        name: NaeemDosh  # Your name for commit author
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'  # Commit message format
    push:
      branch: main  # Specify the branch for pushing updates
  interval: 1m0s  # Check for updates every minute
  sourceRef:
    kind: GitRepository
    name: flux-deployments  # Git repository containing the HelmRelease or manifest files
    namespace: flux-system
  update:
    path: ./flux  # Path to the Helm chart or Kubernetes manifests
    strategy: Setters  # Update strategy (can be "Patch" or "Setters")
  image:
    name: docker.io/muhammadnaeem42/application3  # The image to be updated
    policy:
      semver: ">=1.0.0"  # Version policy for the image
