apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-automation
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: application3-repo
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main # Update this to your branch
    commit:
      author:
        name: NaemDOSH
        email: m.naeem.uet.cs@gmail.com
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main # Update this to your branch
