apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: latest-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: application3-image  
  policy:
    semver:
      range: 5.0.x
