apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main  # Adjust if using a different branch
    commit:
      author:
        email: flux-bot@users.noreply.github.com
        name: Flux Bot
      messageTemplate: |
        Automated image update for {{ .Updated.ImageRef }}  # Custom commit message template
    push:
      branch: main  # Adjust if pushing to a different branch
  interval: 1m  # Check for updates every minute
  sourceRef:
    kind: GitRepository
    name: application3-repo  # Name of the GitRepository resource
  update:
    path: "charts/values.yaml"  # Path to values.yaml, adjust as needed
    strategy: Setters
