apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: latest-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-image  # Reference to the ImageRepository that tracks the image
  policy:
    semver:
      range: ">=1.0.0"  # This selects images that match the semver range
