apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  interval: 5m  # How often to check for new images
  update:
    path: "./charts/application3/values.yaml"  # Path to the values file to update
    strategy: Setters  # Strategy to update the image tag using Setters (or other strategies)
  git:
    # Instead of spec.git.branch, you need to reference your source Git repository correctly
    secretRef:
      name: flux-system-git-ssh  # Secret containing SSH key for Git access
    repository: https://github.com/NaeemDosh/application3  # Your Git repository
    branch: main  # The Git branch to update
  image:
    # The `image` section in ImageUpdateAutomation should refer to the ImagePolicy
    policy:
      name: latest-policy  # The ImagePolicy to track the latest image
    tag: "latest"  # The tag to use (you could also use a tag pattern if desired)
