apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: application3-image  # ImageRepository to track the image
  policy:
    semver:
      range: ">=1.0.0"  # Version range for accepted images
