apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: latest-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-image  # Reference to the ImageRepository
  policy:
    tag:
      pattern: "latest"   # Tag pattern to look for
