apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: docker.io/muhammadnaeem42/application3
  policy:
    semver:
      range: 1.0.x
