apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: application3-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-image  # Name of the ImageRepository resource
  policy:
    tag: "latest"  # Track the 'latest' image tag

