apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main  # The branch you want to track
    commit:
      author:
        email: flux-bot@users.noreply.github.com
        name: Flux Bot
      messageTemplate: |
        Automated image update for {{ .Updated.ImageRef }}
    push:
      branch: main  # Push updates to the same branch or different branch
  interval: 1m  # Frequency to check for new images (every minute)
  sourceRef:
    kind: GitRepository
    name: application3-repo  # The name of your GitRepository resource
  update:
    path: "charts/values.yaml"  # Path to the Helm chart values file to update
    strategy: Setters  # Use Setters strategy to update the tag
