apiVersion: automation.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  interval: 5m  # How often to check for new images
  git:
    repoURL: https://github.com/NaeemDosh/application3  # Your Git repo URL
    branch: main  # The branch to update
    secretRef:
      name: flux-system-git-ssh  # Secret containing SSH key for Git access
  update:
    path: "./charts/application3/values.yaml"  
    strategy: Setters  # Update values using the "Setters" strategy
  image:
    repository: docker.io/muhammadnaeem42/application3  # Docker Hub repo
    policy:
      name: latest-policy  # The ImagePolicy you defined earlier
    tag: "latest"  # Image tag (e.g., "latest", or use a tag pattern from the policy)
