apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: default
spec:
  interval: 1m  # Check for image updates every minute
  sourceRef:
    kind: GitRepository
    name: application3-repo  # Git repository with HelmRelease
    namespace: flux-system
  update:
    path: "charts/application3/values.yaml"  # Path to the Helm values file where the image reference is located
    strategy: Setters  # Update strategy ('Setters' or 'Patch')
  image:
    name: docker.io/muhammadnaeem42/application3  # Image to track for updates
    policy:
      semver: ">=1.0.0"  # Version policy
