apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  git:
    commit:
      author:
        email: m.naeem.uet.cs@gmail.com
        name: NaeemDosh
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main  # Specify the branch for pushing updates to Git
  interval: 1m0s  # Interval at which Flux will check for image updates
  sourceRef:
    kind: GitRepository
    name: flux-deployments  # Name of the Git repository
    namespace: flux-system
  update:
    path: ./flux/flux-system/application3   # Path where the Flux resources are stored (e.g., ImageUpdateAutomation)
    strategy: Setters
    imageRef:
      name: docker.io/muhammadnaeem42/application3  # The image to monitor for updates
      policy:
        semver: ">=1.0.0"  # The version policy for Docker image tags
