apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: application3-repo  # Matches the GitRepository resource
  update:
    path: charts  # Ensure the path points to the directory with HelmRelease
    strategy: Setters
  git:
    checkout:
      ref:
        branch: main
    push:
      branch: main
    commit:
      author:
        name: Flux Bot
        email: flux-bot@users.noreply.github.com
      messageTemplate: |
        Automated image update for {{ .Updated.ImageRef }}
