apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: latest-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-image  # This should refer to your ImageRepository
  policy:
    latest: {}  # Use the `latest` policy type without any additional fields
