apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: latest-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-image  # Reference to the ImageRepository
  policy:
    semver:
      range: ">=1.0.0"  # This ensures you're selecting versions greater than or equal to 1.0.0
