apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: latest-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-image  # Reference to the ImageRepository
  policy:
    # Ensure the correct structure for your policy
    semver:
      range: ">=1.0.0"  # Example of a semver policy (can be adjusted based on your use case)
