apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: application3-image-update
  namespace: default
spec:
  git:
    commit:
      author:
        email: m.naeem.uet.cs@gmail.com
        name: NaeemDosh
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"  # Commit message format
    push:
      branch: main  # Where to push updates
  interval: 1m0s  # Check for updates every minute
  sourceRef:
    kind: GitRepository
    name: flux-deployments  # The GitRepository containing your Helm chart
    namespace: flux-system
  update:
    path: ./charts/application3  # Path to the Helm chart or Kubernetes manifests
    strategy: Setters  # Use Setters strategy for Helm values updates
    imageRef: docker.io/muhammadnaeem42/application3  # Docker image repository
