apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: application3-repository
  policy:
    semver:
      range: ">=1.0.0"  # Update based on your versioning strategy
