apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: application3-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application3-repository  # Reference the ImageRepository created above
  policy:
    semver: ">=1.0.0"  # Version policy to track tags starting from 1.0.0
