apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: docker.io/muhammadnaeem42/application3
    newName: docker.io/muhammadnaeem42/application3
    newTag: v1.1.1  # {"$imagepolicy": "default:application3-image-policy:tag"}

