apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml 
  - ./application3/gitrepository.yaml
  - ./application3/imagerepository.yaml
  - ./application3/imagepolicy.yaml
  - ./application3/helmrelease.yaml
  - ./application3/helmchart.yaml
  - ./application3/imageupdateautomation.yaml
  
  - ./application4/gitrepository.yaml
  - ./application4/imagerepository.yaml
  - ./application4/imagepolicy.yaml
  - ./application4/helmrelease.yaml
  - ./application4/helmchart.yaml
  - ./application4/imageupdateautomation.yaml
