apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  # Application-specific resources
  - ./application3/gitrepository.yaml
  - ./application3/imagerepository.yaml
##  - ./application3/imagePolicy.yaml
  - ./application3/helmrelease.yaml
##  - ./application3/imageUpdateAutomation.yaml
