apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

- ./application4/gitrepository.yaml
- ./application4/imagerepository.yaml
- ./application4/helmrelease.yaml
