apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: application4
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/application4  # Path to Helm chart in the repo
      sourceRef:
        kind: GitRepository
        name: application4-repo
        namespace: flux-system
  values:
    image:
      repository: docker.io/muhammadnaeem42/application4:latest

