apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: application4-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: application4-image  # This must reference the ImageRepository resource
  policy:
    tag: "latest"  # Track the latest image tag

